name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Minify analytics script
        run: |
          npm install terser --save-dev
          npx terser public/analytics.js -o public/analytics.min.js -c -m
          echo "Minification completed!"

      - name: Build project
        run: npm run build
        env:
          AUTH0_DOMAIN=visor.eu.auth0.com
          AUTH0_CLIENT_ID=GBNdD67l9xlmhBQrHedArr422Cjt6r0d


      - name: Create 404.html for React Router
        run: cp build/index.html build/404.html

      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Checking for essential files:"
          [ -f build/index.html ] && echo "✓ index.html exists" || echo "✗ index.html missing"
          [ -f build/404.html ] && echo "✓ 404.html exists" || echo "✗ 404.html missing"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4